apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kidsapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/dainmusty/minikube-project.git
    targetRevision: main
    path: argocd/apps/workloads/kids-app
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kids-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true